<div class="margin-bottom">
	<span class="input">
		<span class="icon-calendar"></span>
		<input type="text" class="input-unstyled datepicker"
		       name="edit_<?=$this->view->key?>_date" value="<?=date('d.m.Y',$this->view->value ? strtotime($this->view->value) : time())?>">
	</span>

	<input name="edit_<?=$this->view->key?>_time" type="text" value="<?=date('H:i:s',$this->view->value ? strtotime($this->view->value) : time())?>" class="input" />
</div>