<option value="<?=$this->view->dataOption[$this->view->idField]?>"<? if(in_array($this->view->dataOption[$this->view->idField], $this->view->db_value)): ?> selected="selected"<? endif; ?>>
	<? for($i=0; $i<$this->view->dataOption['lvl']; $i++): ?>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<? endfor; ?><?if($this->view->dataOption['lvl']):?>-><?endif;?>
	<?=$this->view->dataOption[$this->view->nameField]?>
</option>
