<a href="javascript://" onclick="move('/admin/content/move/model/<?=$this->MODEL_NAME?>/id/<?=$row[$this->idField]?>/type/upup/?<?=$this->urlQueryString?>')"><<</a>
&nbsp;
<a href="javascript://" onclick="move('/admin/content/move/model/<?=$this->MODEL_NAME?>/id/<?=$row[$this->idField]?>/type/up/?<?=$this->urlQueryString?>')"><</a>
&nbsp;
<?=$value?>
&nbsp;&nbsp;
<a href="javascript://" onclick="move('/admin/content/move/model/<?=$this->MODEL_NAME?>/id/<?=$row[$this->idField]?>/type/down/?<?=$this->urlQueryString?>')">></a>
&nbsp;
<a href="javascript://" onclick="move('/admin/content/move/model/<?=$this->MODEL_NAME?>/id/<?=$row[$this->idField]?>/type/downdown/?<?=$this->urlQueryString?>')">>></a>
&nbsp;