<a href="javascript://" onclick="move('/admin/content/move/model/<?=$this->view->MODEL_NAME?>/id/<?=$row[$this->view->idField]?>/type/upup/?<?=$this->view->urlQueryString?>')"><<</a>
&nbsp;
<a href="javascript://" onclick="move('/admin/content/move/model/<?=$this->view->MODEL_NAME?>/id/<?=$row[$this->view->idField]?>/type/up/?<?=$this->view->urlQueryString?>')"><</a>
&nbsp;
<?=$value?>
&nbsp;&nbsp;
<a href="javascript://" onclick="move('/admin/content/move/model/<?=$this->view->MODEL_NAME?>/id/<?=$row[$this->view->idField]?>/type/down/?<?=$this->view->urlQueryString?>')">></a>
&nbsp;
<a href="javascript://" onclick="move('/admin/content/move/model/<?=$this->view->MODEL_NAME?>/id/<?=$row[$this->view->idField]?>/type/downdown/?<?=$this->view->urlQueryString?>')">>></a>
&nbsp;